### ISSUE TITLE
help with gds2bgen

### ISSUE THREAD

**Issue by gianolga** [zhengxwen/gds2bgen#1]
Hello,

Many thanks for creating this tool. I have installed it in R - version 3.6 but I have not managed to make it work. 

I was wondering what "extdata" is referring to in your example, as I am running it in the following way:
> bgen_fn <- system.file("extdata","myworking.bgen", package="gds2bgen")

but then I'm getting an error:

> seqBGEN_Info(bgen_fn)
Error in seqBGEN_Info(bgen_fn) : Can't open the file ''.

Many thanks again
Olga

**Comment by zhengxwen** [comment]
your `bgen_fn` is a blank string.
use `bgen_fn <- "myworking.bgen"` directly.
