### ISSUE TITLE
rename "variant.id" header

### ISSUE THREAD

**Issue by gianolga** [zhengxwen/gds2bgen#2]
Hello,

Many thanks for the tool!! I have managed to convert my bgen files to gds using the pipeline suggested here. However, the downstream analysis of my project requires to read in the gds data and create a GenotypeData class object (I'm using GWASTools for that). However, I'm getting an error that it can't find a "snp.id" column, so I was wondering if I can manually change the variable.id name. Many apologies if this is not exactly the right place for my question. 

Many thanks,
Olga

**Comment by zhengxwen** [comment]
It is sequencing GDS format, not SNP GDS format.
You should use `SeqVarTools` to open the file.

**Comment by wangshuang2024** [comment]
> It is sequencing GDS format, not SNP GDS format. You should use `SeqArray` and `SeqVarTools` to open the file.

hello, I also met the same problem. my gdsfile can successfully opened by "seqOpen" [gdsfile <- seqOpen("C:\\Users\\Desktop\\chr8.gds")] . However, when I used "GdsGenotypeReader" , I got some error waring.
 geno <- GdsGenotypeReader(gdsfile) [Error in index.gdsn(object@handler, varname) : No such GDS node "snp.id"!] 
or 
geno <- GdsGenotypeReader(filename = "chr8.gds")  [Error in openfn.gds(filename = filename, allow.fork = allow.fork) :   The file 'C:\Users\Desktop\chr8.gds' has been created or opened.]

**Comment by zhengxwen** [comment]
Use `seqOpen()` to open your gds file:
```
gdsfile <- SeqArray::seqOpen("chr8.gds")
```

For the association testing, please check the [GENESIS](https://www.bioconductor.org/packages/GENESIS/) package.
